# Generated by Django 5.0.6 on 2024-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordermanagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(to="ordermanagement.item"),
        ),
    ]
