# Generated by Django 5.0.6 on 2024-06-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_drink_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
