# Generated by Django 5.0.6 on 2024-06-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_drink_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='price',
        ),
    ]
