# Generated by Django 5.0.6 on 2024-06-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_drink_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
